# Generated by Django 4.1 on 2022-09-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_alimento', models.CharField(max_length=200)),
                ('desc_alimento', models.CharField(max_length=200)),
                ('precio_alimento', models.IntegerField()),
            ],
        ),
    ]
